name: Test Dev

on:
  push:
    branches:
      - dev

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=4096'

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Build
        run: pnpm build

  notify-on-failure:
    name: Notify Feishu
    runs-on: ubuntu-latest
    # needs: [unit-test, lint]
    needs: install-and-build
    if: always()
    steps:
      - name: Notify Feishu
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "msg_type": "text",
            "content": {
              "text": "CI 构建通知\n仓库: ${{ github.repository }}\n分支: ${{ github.ref }}\n状态: ${{ job.status }}\n构建链接: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
          }' \
          ${{ secrets.FEISHU_WEBHOOK_URL }}
