name: Docker Custom Image CI
run-name: Build ${{ github.ref_name }} - ${{ github.actor }}

on:
  pull_request:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Google Cloud
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Set short SHA
        id: short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: ./docker/images/n8n-custom/Dockerfile
          build-args: |
            N8N_RELEASE_TYPE=development
          platforms: linux/amd64
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/agentflow:${{ env.SHORT_SHA }}
            ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/agentflow:latest

      - name: Notify Feishu
        if: always()
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"msg_type\": \"text\",
            \"content\": {
              \"text\": \"Docker 镜像构建通知\n仓库: ${{ github.repository }}\n分支: ${{ github.ref_name }}\n标签: agentflow:${SHORT_SHA}\n状态: ${{ job.status }}\n构建链接: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n镜像地址: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/agentflow:${SHORT_SHA}\"
            }
          }" \
          ${{ secrets.FEISHU_WEBHOOK_URL }}
